name = "teakzc/crunchywrapper"
version = "0.1.5"
description = "crunchyroll (ffrostfall/crunchyroll, but i forked it and it will be used here) wrapper with animation fades and motor6d support"
authors = ["teakzc"]
repository = "https://github.com/teakzc/crunchywrapper"
license = "MIT"
includes = ["pesde.toml", "README.md", "LICENSE", "src/**/*.luau"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.1", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
crunchyroll = { wally = "teakzc/crunchyroll", version = "^0.1.1" }